"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = __importDefault(require("fs"));
const path_1 = __importDefault(require("path"));
const core_1 = require("@actions/core");
const github_action_helper_1 = require("@technote-space/github-action-helper");
const safe_1 = __importDefault(require("colors/safe"));
const constant_1 = require("../constant");
const { getWorkspace, escapeRegExp, isSemanticVersioningTagName } = github_action_helper_1.Utils;
const normalizeVersion = (version) => version.replace(/^v/, '');
exports.getPackageDir = () => core_1.getInput('PACKAGE_DIR') || getWorkspace();
exports.getPackageFileName = () => core_1.getInput('PACKAGE_NAME') || constant_1.DEFAULT_PACKAGE_NAME;
exports.getPackagePath = () => path_1.default.resolve(exports.getPackageDir(), exports.getPackageFileName());
exports.getPackageData = () => JSON.parse(fs_1.default.readFileSync(exports.getPackagePath(), { encoding: 'utf-8' }));
exports.getPackageVersion = () => exports.getPackageData()['version'];
exports.getTestTagPrefix = () => core_1.getInput('TEST_TAG_PREFIX') || constant_1.DEFAULT_TEST_TAG_PREFIX;
const getTestTagPrefixRegExp = () => new RegExp('^' + escapeRegExp(exports.getTestTagPrefix()));
exports.isTestTag = (tagName) => !!exports.getTestTagPrefix() && getTestTagPrefixRegExp().test(tagName);
exports.getTestTag = (tagName) => tagName.replace(getTestTagPrefixRegExp(), '');
exports.getPackageVersionToUpdate = (tagName) => normalizeVersion(exports.isTestTag(tagName) ? exports.getTestTag(tagName) : tagName);
exports.isRequiredUpdate = (packageVersion, tagName) => normalizeVersion(packageVersion) !== exports.getPackageVersionToUpdate(tagName);
exports.isValidTagName = (tagName) => isSemanticVersioningTagName(exports.getPackageVersionToUpdate(tagName));
exports.getReplaceResultMessages = (results) => results.map(result => `${result.hasChanged ? safe_1.default.green('✔') : safe_1.default.red('✖')} ${result.file}`);
exports.getCommitMessage = () => core_1.getInput('COMMIT_MESSAGE') || constant_1.DEFAULT_COMMIT_MESSAGE;
